name: Restart PM2 on Push

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку

jobs:
  restart:

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: v12.22.12  # Укажите версию Node.js, если необходимо

    - name: Restart PM2
      run: pm2 restart my-app  # Укажите имя вашего PM2 приложения